# Generated by Django 2.0 on 2018-01-04 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('img_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Mug', 'Mug'), ('Blouse', 'Blouse')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 16, 18, 40, 466836)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 16, 18, 40, 466155)),
        ),
    ]
