# Generated by Django 2.0 on 2018-01-09 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180109_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 17, 24, 26, 655045)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 17, 24, 26, 654329)),
        ),
    ]
